version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run:
          name: build image
          command: docker build -t robinho .
      - run:
          name: run tests
          command: docker run --rm robinho python3 -m unittest tests/*_test.py
