version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: auth
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo $DOCKERHUB_PASS | docker login --username=$DOCKERHUB_USER --password-stdin
            echo $HEROKU_KEY | docker login --username=_  --password-stdin registry.heroku.com
            # fi
      - run:
          name: api
          command: ./api/deploy.sh
