version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: auth
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
              docker push fakenewsdetector/api

              docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
            fi
      - run:
          name: api
          command: ./api/deploy.sh
