version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: fetch existing image
          command: |
            docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
            docker pull registry.heroku.com/robinho/web
      - run:
          name: build
          command: make build
      - run:
          name: run tests
          command: make test
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push registry.heroku.com/robinho/web
            fi
